aws_edfcatalogoqr/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

app/routes.py
# Primero las importaciones necesarias
from flask import (
    Blueprint,
    flash,
    current_app,
    render_template,
    url_for,
    redirect,
    request,
    abort,
    send_file,
    session,
    jsonify,
)
from flask_login import login_user, current_user, logout_user, login_required
from functools import wraps
import os
import logging
import boto3
from werkzeug.datastructures import FileStorage
from mongoengine.queryset.visitor import Q
from mongoengine.errors import NotUniqueError
from datetime import datetime
import qrcode

# Importaciones locales
from app.models import User, Container
from app.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    ContainerForm,
    RequestResetForm,
    ResetPasswordForm,
    DeleteAccountForm,
    ContactForm,
    ChangePasswordForm,
    SearchContainerForm,
    EditContainerForm,
    DeleteImageForm,
)
from app.utils import (
    save_profile_picture,
    save_container_picture,
    send_reset_email,
    save_qr_image,
    admin_required,
    normalize_name,
)
from app.extensions import db, bcrypt, mail
from flask_mail import Message

# Configuración del Blueprint
main = Blueprint("main", __name__)


# Configuración mejorada del logger
def setup_logger():
    logger = logging.getLogger(__name__)

    # Evitar duplicación de handlers
    if not logger.handlers:
        logger.setLevel(logging.INFO)

        # Crear el directorio de logs si no existe
        os.makedirs("logs", exist_ok=True)

        # Configurar el RotatingFileHandler
        file_handler = logging.handlers.RotatingFileHandler(
            "logs/app.log",
            maxBytes=1024 * 1024,  # 1MB
            backupCount=10,
            encoding="utf-8",
        )

        # Configurar el formato
        formatter = logging.Formatter(
            "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        )
        file_handler.setFormatter(formatter)

        # Añadir el handler al logger
        logger.addHandler(file_handler)

    return logger


# Inicializar el logger
logger = setup_logger()

# Inicializar el cliente de S3
try:
    s3 = boto3.client("s3")
except Exception as e:
    logger.error(f"Error al inicializar el cliente S3: {e}")
    s3 = None


# Decorador para manejo de errores
def handle_errors(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        try:
            return f(*args, **kwargs)
        except Exception as e:
            logger.error(f"Error en {f.__name__}: {str(e)}", exc_info=True)
            flash("Ha ocurrido un error inesperado", "danger")
            return redirect(url_for("main.home"))

    return decorated_function


@main.route("/")
@main.route("/home")
@handle_errors
def home():
    try:
        session.pop("show_welcome_modal", None)
        current_year = datetime.now().year
        return render_template("home.html", title="Inicio", current_year=current_year)
    except Exception as e:
        logger.error(f"Error en la ruta home: {e}")
        raise


# Función auxiliar para verificar imágenes
def verify_container_images(container):
    """Verifica y retorna solo las imágenes válidas de un contenedor."""
    valid_images = []
    for image in container.image_files:
        image_path = os.path.join(
            current_app.root_path, "static", "container_pics", image
        )
        if os.path.exists(image_path):
            valid_images.append(image)
        else:
            logger.warning(f"Imagen no encontrada: {image_path}")
    return valid_images


@main.route("/test")
def test():
    return "La aplicación está funcionando"


@main.route("/about")
def about():
    return render_template("about.html", title="Acerca de")


@main.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.welcome"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        if form.picture.data:
            picture_file = save_profile_picture(form.picture.data)
            user.image_file = picture_file
        user.save()
        flash("Tu cuenta ha sido creada! Ahora puedes iniciar sesión", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Registro", form=form)


@main.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("users.logout_page"))


@main.route("/logout_page")
def logout_page():
    return render_template("logout.html")


@main.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()

    # Procesar el formulario si se están enviando los datos
    if form.validate_on_submit():
        try:
            # Logging del estado antes de la actualización
            current_app.logger.info(
                f"Iniciando actualización de cuenta para el usuario: {current_user.username}"
            )
            current_app.logger.info(
                f"Información recibida - Username: {form.username.data}, Email: {form.email.data}, "
                f"Address: {form.address.data}, Phone: {form.phone.data}"
            )

            # Manejar la actualización de la foto de perfil
            if form.picture.data:
                current_app.logger.info(
                    f"Actualizando foto de perfil para el usuario: {current_user.username}"
                )
                try:
                    picture_file = save_profile_picture(form.picture.data)
                    current_user.image_file = picture_file
                    current_app.logger.info(
                        f"Foto de perfil actualizada: {picture_file}"
                    )
                except Exception as e:
                    current_app.logger.error(
                        f"Error al actualizar la foto de perfil para {current_user.username}: {e}"
                    )
                    flash(
                        "Error al actualizar la foto de perfil. Intenta nuevamente.",
                        "danger",
                    )
                    return redirect(url_for("users.account"))

            # Verificar si el nombre de usuario ha cambiado
            if form.username.data != current_user.username:
                current_app.logger.info(
                    f"El nombre de usuario ha cambiado de {current_user.username} a {form.username.data}"
                )

            # Actualizar los campos del usuario
            current_user.username = form.username.data
            current_user.email = form.email.data
            current_user.address = form.address.data
            current_user.phone = form.phone.data

            # Guardar los cambios en la base de datos
            current_user.save()
            current_app.logger.info(
                f"Cuenta actualizada exitosamente para el usuario: {current_user.username}"
            )

            flash("Tu cuenta ha sido actualizada exitosamente!", "success")

            # Redirigir para evitar el reenvío del formulario al actualizar
            return redirect(url_for("users.account"))

        except Exception as e:
            # Capturar y registrar errores si ocurre un problema durante la actualización
            current_app.logger.error(
                f"Error actualizando la cuenta para el usuario {current_user.username}: {e}"
            )
            flash(
                "Ocurrió un error al actualizar la cuenta. Intenta de nuevo.", "danger"
            )

    # Mostrar los datos actuales si es un GET
    elif request.method == "GET":
        # Logging de la carga de los datos del usuario
        current_app.logger.info(f"Cargando datos del usuario: {current_user.username}")
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.address.data = current_user.address
        form.phone.data = current_user.phone

    # Obtener la imagen de perfil para mostrarla en la vista
    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)

    # Logging de la imagen cargada
    current_app.logger.info(
        f"Mostrando imagen de perfil para el usuario {current_user.username}: {current_user.image_file}"
    )

    return render_template(
        "account.html", title="Cuenta", image_file=image_file, form=form
    )


@main.route("/contacto", methods=["GET", "POST"])
def contacto():
    form = ContactForm()
    if form.validate_on_submit():
        try:
            msg = Message(
                subject=f"Nuevo mensaje de contacto de {form.name.data}",
                sender=current_app.config["MAIL_USERNAME"],
                recipients=[current_app.config["MAIL_DEFAULT_SENDER"]],
                reply_to=form.email.data,
            )
            msg.body = f"""
            Nombre: {form.name.data}
            Email: {form.email.data}
            Mensaje:
            {form.message.data}
            """

            mail.send(msg)
            flash("Tu mensaje ha sido enviado correctamente!", "success")
            return redirect(url_for("main.home"))
        except Exception as e:
            current_app.logger.error(f"Error enviando email: {str(e)}")
            flash(
                "Hubo un error al enviar el mensaje. Por favor, intenta más tarde.",
                "danger",
            )
    return render_template("contacto.html", title="Contacto", form=form)


@main.route("/change_password", methods=["GET", "POST"])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.check_password(form.current_password.data):
            hashed_password = bcrypt.generate_password_hash(
                form.new_password.data
            ).decode("utf-8")

app/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from flask_login import login_user, current_user, logout_user, login_required
from app.models import User
from app.forms import (
    LoginForm,
    RegistrationForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
    ChangePasswordForm,
    DeleteAccountForm,
)
from app.utils import save_profile_picture, send_reset_email
from app.extensions import bcrypt
import logging
from pathlib import Path  # Asegúrate de importar Path desde pathlib

users_bp = Blueprint("users", __name__)

# Configuración del logger
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# Asegurar que el directorio de logs existe
Path("logs").mkdir(exist_ok=True)

# Configurar RotatingFileHandler para mejor manejo de logs
handler = logging.handlers.RotatingFileHandler(
    "logs/app.log", maxBytes=1024 * 1024, backupCount=5, encoding="utf-8"  # 1MB
)
formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
handler.setFormatter(formatter)
logger.addHandler(handler)


@users_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = LoginForm()
    if form.validate_on_submit():
        # Buscar usuario por email o nombre de usuario
        user = (
            User.objects(email=form.email_or_username.data).first()
            or User.objects(username=form.email_or_username.data).first()
        )

        if user:
            try:
                # Verificar contraseña
                if bcrypt.check_password_hash(user.password, form.password.data):
                    login_user(user, remember=form.remember.data)
                    next_page = request.args.get("next")
                    return (
                        redirect(next_page)
                        if next_page
                        else redirect(url_for("main.home"))
                    )
                else:
                    flash("Contraseña incorrecta", "danger")
            except ValueError as e:
                flash(
                    "Error al verificar la contraseña. Por favor, intenta restablecer tu contraseña.",
                    "danger",
                )
                logger.error(
                    f"Error al verificar la contraseña para el usuario {user.username}: {e}"
                )
        else:
            flash("Email o nombre de usuario incorrecto", "danger")
    return render_template("login.html", title="Iniciar Sesión", form=form)


@users_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
    if form.picture.data:
        picture_file = save_profile_picture(form.picture.data)
        user.image_file = picture_file
        user.save()
        flash("Tu cuenta ha sido creada! Ahora puedes iniciar sesión", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Registro", form=form)


@users_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("users.logout_page"))


@users_bp.route("/logout_page")
def logout_page():
    # Renderiza una página de confirmación de cierre de sesión
    return render_template("logout.html")


@users_bp.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_profile_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.address = form.address.data
        current_user.phone = form.phone.data
        current_user.save()
        flash("Tu cuenta ha sido actualizada!", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.address.data = current_user.address
        form.phone.data = current_user.phone
    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)

    return render_template(
        "account.html", title="Account", image_file=image_file, form=form
    )


@users_bp.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.objects(email=form.email.data).first()
        if user:
            send_reset_email(user)
            flash(
                "Se ha enviado un email con instrucciones para resetear tu contraseña.",
                "info",
            )
            return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="Reset Password", form=form)


@users_bp.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("Token inválido o expirado", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        user.save()
        flash("Tu contraseña ha sido actualizada!", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_password.html", title="Reset Password", form=form)


@users_bp.route("/change_password", methods=["GET", "POST"])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if bcrypt.check_password_hash(
            current_user.password, form.current_password.data
        ):
            hashed_password = bcrypt.generate_password_hash(
                form.new_password.data
            ).decode("utf-8")
            current_user.password = hashed_password
            current_user.save()
            flash("Tu contraseña ha sido actualizada!", "success")
            return redirect(url_for("users.account"))
        else:
            flash("Contraseña actual incorrecta", "danger")
    return render_template(
        "change_password.html", title="Cambiar Contraseña", form=form
    )


@users_bp.route("/delete_account", methods=["GET", "POST"])
@login_required
def delete_account():
    form = DeleteAccountForm()
    if form.validate_on_submit():
        if form.confirm.data:
            user = current_user._get_current_object()
            # Eliminar contenedores del usuario
            from app.models import Container

            Container.objects(user=user).delete()
            user.delete()
            logout_user()
            flash("Tu cuenta ha sido eliminada", "success")
            return redirect(url_for("main.home"))
    return render_template("delete_account.html", title="Eliminar Cuenta", form=form)

app/templates/change_password.html
{% extends "layout.html" %}
{% block content %}
    <h1>Cambio de contraseña</h1>
    <div class="content-section">
        <h1>Cambio de Contraseña</h1>
        <form method="POST" action="{{ url_for('users.change_password') }}">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.current_password.label(class="form-control-label") }}
                <div class="input-group">
                    {% if form.current_password.errors %}
                        {{ form.current_password(class="form-control form-control-lg
                                                is-invalid", id="currentPassword") }}
                        <div class="invalid-feedback">
                            {% for error in form.current_password.errors %}<span>{{ error }}</span>{% endfor %}
                        </div>
                    {% else %}
                        {{ form.current_password(class="form-control
                                                form-control-lg", id="currentPassword") }}
                    {% endif %}
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary"
                                type="button"
                                onclick="togglePassword('currentPassword')">
                            <i class="fas fa-eye"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.new_password.label(class="form-control-label") }}
                <div class="input-group">
                    {% if form.new_password.errors %}
                        {{ form.new_password(class="form-control form-control-lg
                                                is-invalid", id="newPassword") }}
                        <div class="invalid-feedback">
                            {% for error in form.new_password.errors %}<span>{{ error }}</span>{% endfor %}
                        </div>
                    {% else %}
                        {{ form.new_password(class="form-control
                                                form-control-lg", id="newPassword") }}
                    {% endif %}
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary"
                                type="button"
                                onclick="togglePassword('newPassword')">
                            <i class="fas fa-eye"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                <div class="input-group">
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg
                                                is-invalid", id="confirmPassword") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}<span>{{ error }}</span>{% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control
                                                form-control-lg", id="confirmPassword") }}
                    {% endif %}
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary"
                                type="button"
                                onclick="togglePassword('confirmPassword')">
                            <i class="fas fa-eye"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <a href="{{ url_for('main.welcome') }}" class="btn btn-secondary">Volver a Opciones</a>
            </div>
        </form>
    </div>
    <script>
    function togglePassword(fieldId) {
        var field = document.getElementById(fieldId);
        var fieldType = field.getAttribute('type');
        if (fieldType === 'password') {
            field.setAttribute('type', 'text');
        } else {
            field.setAttribute('type', 'password');
        }
    }
    </script>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>
            {% block title %}EDF Catalogación QR{% endblock %}
        </title>
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/style.css') }}" />
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
              rel="stylesheet" />
        <!-- Favicon -->
        <link rel="icon"
              href="{{ url_for('static', filename='favicon.ico') }}"
              type="image/x-icon" />
        <!-- CSS -->
        <style>
            body,
            html {
                height: 100%;
                margin: 0;
                display: flex;
                flex-direction: column;
                padding-top: 76px; /* Altura del navbar + padding */
                padding-bottom: 60px; /*  Altura del footer */
            }

            .navbar-container {
                background-color: #343a40;
                position: fixed;
                top: 0;
                width: 100%;
                z-index: 1000;
            }

            .container-content {
                flex: 1;
                padding: 20px;
                margin-bottom: 60px; /* Espacio para el footer */
            }

            footer {
                background-color: #343a40;
                color: white;
                padding: 10px 0;
                position: fixed;
                bottom: 0;
                width: 100%;
                z-index: 1000;
            }

            #scrollTopBtn {
                display: none;
                position: fixed;
                bottom: 80px;
                right: 20px;
                z-index: 99;
                border: none;
                outline: none;
                background-color: #343a40;
                color: white;
                cursor: pointer;
                padding: 10px;
                border-radius: 50%;
                font-size: 18px;
                transition: background-color 0.3s;
            }

            #scrollTopBtn:hover {
                background-color: #555;
            }

            .alert-container {
                margin-top: 20px;
            }
        </style>
    </head>
    <body>
        <!-- Navbar -->
        <div class="navbar-container">
            <nav class="navbar navbar-expand-lg navbar-dark">
                <div class="container">
                    <a class="navbar-brand" href="{{ url_for('main.home') }}">
                        <img src="{{ url_for('static', filename='images/logo.png') }}"
                             width="50"
                             height="50"
                             class="d-inline-block align-middle"
                             alt="EDF Logo" />
                        EDF Catalogación QR
                    </a>
                    <button class="navbar-toggler"
                            type="button"
                            data-toggle="collapse"
                            data-target="#navbarNav">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('main.home') }}">Inicio</a>
                            </li>
                            {% if current_user.is_authenticated %}
                                <!-- Menú para usuarios autenticados -->
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('users.account') }}">Cuenta</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('main.create_container') }}">Crear Contenedor</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('main.list_containers') }}">Mis Contenedores</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('main.about') }}">Acerca de</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('main.contacto') }}">Contacto</a>
                                </li>
                                {% if current_user.is_admin %}
                                    <!-- Menú de administrador -->
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle"
                                           href="#"
                                           id="adminDropdown"
                                           data-toggle="dropdown">Admin</a>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" href="{{ url_for('admin.search_user') }}">Buscar Usuario</a>
                                            <a class="dropdown-item" href="{{ url_for('admin.list_users') }}">Listar Usuarios</a>
                                            <a class="dropdown-item" href="{{ url_for('admin.admin_search_containers') }}">Contenedores</a>
                                        </div>
                                    </li>
                                {% endif %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('users.logout') }}">Cerrar Sesión</a>
                                </li>
                            {% else %}
                                <!-- Menú para usuarios no autenticados -->
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('users.login') }}">Iniciar Sesión</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('users.register') }}">Registrarse</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <!-- Mensajes Flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if
                messages %}
                <div class="container alert-container">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible fade show"
                             role="alert">
                            {{ message }}
                            <button type="button" class="close-alert" data-dismiss="alert">
                                <span>&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
        <!-- Contenido Principal -->
        <div class="container-content">
            {% block content %}{% endblock %}
        </div>
        <!-- Footer -->
        <footer class="text-center">
            <div class="container-footer">
                <a href="{{ url_for('main.contacto') }}" class="text-white">Contacto - Eugenio de Frutos</a>
                <p class="mb-0">
                    &copy; {{ current_year }} EDF Proyectos. Todos los derechos
                    reservados.
                </p>
            </div>
        </footer>
        <!-- Botón Scroll Top -->
        <button onclick="scrollToTop()" id="scrollTopBtn" class="btn btn-primary">
            <i class="fas fa-arrow-up"></i>
        </button>
        <!-- Scripts -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script>
            // Función para imprimir detalles
            function printDetail(containerId) {
                window.open(
                    '/containers/' + containerId + '/print_detail',
                    '_blank',
                );
            }

            // Control del botón scroll top
            window.onscroll = function () {
                var scrollTopBtn = document.getElementById('scrollTopBtn');
                if (
                    document.body.scrollTop > 100 ||
                    document.documentElement.scrollTop > 100
                ) {
                    scrollTopBtn.style.display = 'block';
                } else {
                    scrollTopBtn.style.display = 'none';
                }
            };

            function scrollToTop() {
                window.scrollTo({ top: 0, behavior: 'smooth' });
            }
        </script>
    </body>
</html>